apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: life-clinic-aws-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
  region: us-east-1